color0 #262b2c
color1 #fd4663
color2 #c1cfd2
color3 #c3cad0
color4 #c4c8cf
color5 #b6c5c9
color6 #b8c0c7
color7 #f2f3f3
color8 #646b6c
color9 #fd4663
color10 #c1cfd2
color11 #c3cad0
color12 #c4c8cf
color13 #b6c5c9
color14 #b8c0c7
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #1c2021
background            #1c2021
foreground            #f2f3f3
selection_foreground  #b0b4b5
selection_background  #262b2c
active_border_color   #c1cfd2
inactive_border_color #262b2c
url_color             #c1cfd2

active_tab_foreground   #1c2122
active_tab_background   #c1cfd2
inactive_tab_foreground #b0b4b5
inactive_tab_background #262b2c
cursor_trail_color      #b0b4b5
